#!/bin/sh

case "$1" in
  start)
        echo "Starting network..."
		ifup -a
        ;;
  stop)
		echo "Stop network..."
		ifdown -a
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

